# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pet < Formula
  desc "Simple command-line snippet manager"
  homepage "https://github.com/knqyf263/pet"
  version "0.6.0"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.0/pet_0.6.0_darwin_amd64.tar.gz"
      sha256 "567208905a7df9293146b60824d22d5a15959bd30e5a8bdafbb50fc30ef0f3de"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.0/pet_0.6.0_darwin_arm64.tar.gz"
      sha256 "a8a0ef2b54e0117bcc05fb4c0ce7c558245623be7c78db66498ff1a22e415bde"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.0/pet_0.6.0_linux_armv6.tar.gz"
      sha256 "fd9910024a7853a7f78eabbbfcffe32c4fdacc9ba09948274fc32b8295be4e0c"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.0/pet_0.6.0_linux_arm64.tar.gz"
      sha256 "875721c2a3a1772d6a5c846b188c5bdf53650693af8e5f16c46c78861e3aca2f"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.0/pet_0.6.0_linux_amd64.tar.gz"
      sha256 "76d646750d98eb1dbe9740fbf02a823eec6440610b8fab0fec9ac49f03ccb632"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  test do
    system "#{bin}/pet"
  end
end
