# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pet < Formula
  desc "Simple command-line snippet manager"
  homepage "https://github.com/knqyf263/pet"
  version "0.6.3"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.3/pet_0.6.3_darwin_amd64.tar.gz"
      sha256 "279acdaf3e69fd92d23a65efcc8e088ca2b4b9c9e5ee097a16ee1c42470ee8ee"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.3/pet_0.6.3_darwin_arm64.tar.gz"
      sha256 "1a9fa91fad2549b7f4d08589a04a022095d69dcd220313375bb559da21e83fd4"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.3/pet_0.6.3_linux_amd64.tar.gz"
      sha256 "cfa910b3eda19a119386734c7017b8c471ac681686b80d1d48eeaa6e8873ef71"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.3/pet_0.6.3_linux_armv6.tar.gz"
      sha256 "4c76c39e5264a6a0c7f0f2fb35b4c4e941c5fb4a61fbd2bedd77c96ec01e9c8f"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knqyf263/pet/releases/download/v0.6.3/pet_0.6.3_linux_arm64.tar.gz"
      sha256 "480ac3791a4a73287a7d404ad1bd2f162a9b0a25a8dec70cd8b0c05f9b8b09f0"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  test do
    system "#{bin}/pet"
  end
end
